trigger:
  branches:
    include:
      - main

stages:
- stage: DeployKeyVault
  jobs:
  - job: Deploy
    pool:
      name: windowsagent  # Custom agent pool name
    
    steps:
    - checkout: self

    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: 'AzureRM-Connection'
        subscriptionId: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'
        action: 'Create Or Update Resource Group'
        resourceGroupName: 'my-rg'
        location: 'eastus'
        templateLocation: 'Linked artifact'
        csmFile: 'infra/keyvault.json'
        csmParametersFile: 'infra/keyvault.parameters.json'
        deploymentMode: 'Incremental'

- stage: UseSecrets
  dependsOn: DeployKeyVault
  jobs:
  - job: RetrieveSecrets
    pool:
      name: windowsagent  # Same custom pool
    
    steps:
    - task: AzureKeyVault@2
      inputs:
        azureSubscription: 'AzureRM-Connection'
        KeyVaultName: 'my-secure-kv'
        SecretsFilter: '*'
        RunAsPreJob: true

    - script: echo "Secret value is $(MySecret)"
      displayName: 'Print Secret'