trigger:
  branches:
    include:
      - main

pool:
  name: windowsagent  # Replace with your actual agent pool name

steps:
- checkout: none  # Skip repo checkout since you're using local files

- script: |
    echo "Initializing Terraform..."
    terraform init
  displayName: 'Terraform Init'
  workingDirectory: 'C:\PhillipG'

- script: |
    echo "Planning Terraform deployment..."
    terraform plan -var-file="terraform.tfvars" -out=tfplan
  displayName: 'Terraform Plan'
  workingDirectory: 'C:\PhillipG'

- script: |
    echo "Applying Terraform plan..."
    terraform apply -var-file="terraform.tfvars" -auto-approve tfplan
  displayName: 'Terraform Apply'
  workingDirectory: 'C:\PhillipG'