trigger:
  branches:
    include:
      - main

pool:
  name: 'AzureVM-Pool'

steps:
- script: echo "Hello from windows-vm!"
  displayName: 'Test Agent Connection'

- powershell: |
    Write-Host "Running on: $env:COMPUTERNAME"
    Write-Host "Agent Version: $env:AGENT_VERSION"
  displayName: 'Show Agent Info'