trigger:
  branches:
    include:
      - main

pool:
  vmImage: windowsagent

variables:
  TF_VAR_subscription_id: $(subscriptionId)
  TF_VAR_tenant_id: $(tenantId)
  TF_VAR_client_id: $(servicePrincipalId)
  TF_VAR_client_secret: $(servicePrincipalKey)
  TF_VAR_object_id: $(objectId)

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'AzureRM-Connection'  # Your service connection name
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      curl -sL https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip -o terraform.zip
      unzip terraform.zip
      sudo mv terraform /usr/local/bin/
      terraform -version

      cd terraform  # adjust if your .tf files are elsewhere
      terraform init
      terraform plan -out=tfplan
      terraform apply -auto-approve tfplan