trigger:
  - main

pool:
  name: windowsagent

variables:
  TF_BACKEND_RESOURCE_GROUP_NAME: my-resource-group
  TF_BACKEND_STORAGE_ACCOUNT_NAME: mystorageaccount
  TF_BACKEND_CONTAINER_NAME: tfstate
  TF_BACKEND_KEY: terraform.tfstate

stages:
  - stage: Terraform
    jobs:
      - job: Init
        steps:

          - powershell: |
              Invoke-WebRequest -Uri https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_windows_amd64.zip -OutFile terraform.zip
              Expand-Archive terraform.zip -DestinationPath $Env:USERPROFILE\bin
              $env:PATH += ";$Env:USERPROFILE\bin"
              terraform -version
            displayName: 'Install Terraform'

          - task: AzureCLI@2
            inputs:
              azureSubscription: AzureRM-Connection  # ← your real service connection name
              scriptType: ps
              scriptLocation: inlineScript
              inlineScript: |
                terraform init `
                  -backend-config="resource_group_name=$(TF_BACKEND_RESOURCE_GROUP_NAME)" `
                  -backend-config="storage_account_name=$(TF_BACKEND_STORAGE_ACCOUNT_NAME)" `
                  -backend-config="container_name=$(TF_BACKEND_CONTAINER_NAME)" `
                  -backend-config="key=$(TF_BACKEND_KEY)"
            displayName: 'Terraform Init'
