trigger:
  branches:
    include:
      - main

pool:
  name: windowsagent  # Replace with your actual agent pool name

variables:
  subscriptionId: '7b4156be-c801-4a1d-a9c5-418dc1158bb7'
  resourceGroup: 'rg-phillipg-dev'
  location: 'westus2'
  storageAccount: 'phillipgstorage'
  containerName: 'tfstate'
  keyVaultName: 'phillipg-kv'

# 🔐 Retrieve secrets from Azure Key Vault
steps:
- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'AzureRM-Connection'
    KeyVaultName: '$(keyVaultName)'
    SecretsFilter: '*'
    RunAsPreJob: true

# 🔧 Bootstrap Azure Backend Resources
- powershell: |
    az login --service-principal `
      --username "$env:client_id" `
      --password "$env:client_secret" `
      --tenant "$env:tenant_id"

    # ✅ Confirm login worked
    az account show

    # 🌐 DNS check for storage endpoint
    nslookup "$env:storageAccount".blob.core.windows.net

    az account set --subscription "$env:subscriptionId"

    az group create --name "$env:resourceGroup" --location "$env:location"

    az keyvault create --name "$env:keyVaultName" --resource-group "$env:resourceGroup" --location "$env:location"

    az storage account create --name "$env:storageAccount" --resource-group "$env:resourceGroup" --location "$env:location" --sku Standard_LRS --kind StorageV2

    az storage container create --name "$env:containerName" --account-name "$env:storageAccount"
  displayName: 'Bootstrap Azure Backend'
  workingDirectory: 'C:\PhillipG'

# ⏳ Wait for Azure to finalize resource creation
- powershell: |
    Write-Host "Waiting for Azure resources to become available..."
    Start-Sleep -Seconds 30
  displayName: 'Wait for Azure Resource Propagation'

# ✅ Verify Resource Group and Storage Account
- powershell: |
    az group show --name "$env:resourceGroup"
    az storage account show --name "$env:storageAccount" --resource-group "$env:resourceGroup"
  displayName: 'Verify Azure Resources'
  workingDirectory: 'C:\PhillipG'

# 🧱 Terraform Init
- powershell: |
    terraform init
  displayName: 'Terraform Init'
  workingDirectory: 'C:\PhillipG'

# 📐 Terraform Plan
- powershell: |
    terraform plan -var-file="C:/PhillipG/terraform.tfvars" -out=tfplan
  displayName: 'Terraform Plan'
  workingDirectory: 'C:\PhillipG'