trigger:
- main

pool:
  name: AzureVM-Pool

variables:
  terraformVersion: '1.8.5'
  terraformPath: 'C:\terraform\terraform.exe'
  workingDir: '$(Pipeline.Workspace)/tf'

steps:

- checkout: self

- task: PowerShell@2
  displayName: 'Create Workspace Folder'
  inputs:
    targetType: 'inline'
    script: |
      New-Item -ItemType Directory -Force -Path "$(workingDir)"
- task: PowerShell@2
  displayName: 'Inject main.tf from script'
  inputs:
    targetType: 'filePath'
    filePath: '$(Build.SourcesDirectory)/scripts/inject-main.tf.ps1'



- task: PowerShell@2
  displayName: 'Install Terraform'
  inputs:
    targetType: 'inline'
    script: |
      if (-Not (Test-Path "$(terraformPath)")) {
        Write-Host "Installing Terraform $(terraformVersion)..."
        New-Item -ItemType Directory -Force -Path "C:\terraform" | Out-Null
        $zipUrl = "https://releases.hashicorp.com/terraform/$(terraformVersion)/terraform_$(terraformVersion)_windows_amd64.zip"
        Invoke-WebRequest -Uri $zipUrl -OutFile "terraform.zip"
        Expand-