trigger:
  branches:
    include:
      - main  # or master, depending on your default branch

pool:
  vmImage: 'macos-latest'  # or 'windows-latest' for .NET or 'macos-latest' for MacOS


steps:
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'  # Or your build folder
    includeRootFolder: false
    archiveFile: '$(Build.ArtifactStagingDirectory)/your-artifact.zip'

- task: NodeTool@0  # Use NodeTool task to install Node.js on the agent
  inputs:
    versionSpec: '16.x'  # specify the Node.js version
    addToPath: true

- script: |
    npm install
    npm run build  # Add your build step here, if applicable
  displayName: 'Install dependencies and build'

- task: AzureWebApp@1  # Azure Web App Deployment task
  inputs:
    azureSubscription: 'AzureRM-Connection'  # Connect your Azure subscription to Azure DevOps
    appName: 'YourWebAppName69'  # The name of your Azure Web App
    package: $(Build.ArtifactStagingDirectory)/your-artifact.zip  # Path to your app's build artifact (make sure to use .zip or .tar.gz for Azure Web Apps)
