trigger:
  branches:
    include:
      - main

pool:
  name: windowsagent  # Replace with your actual agent pool name

variables:
  TF_VAR_subscription_id: $(subscriptionId)
  TF_VAR_tenant_id: $(tenantId)
  TF_VAR_client_id: $(servicePrincipalId)
  TF_VAR_client_secret: $(servicePrincipalKey)
  TF_VAR_object_id: $(objectId)

steps:
- checkout: none  # Skip repo checkout since you're using a local folder

- script: |
    echo "Installing Terraform..."
    curl -o terraform.zip https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_windows_amd64.zip
    powershell -Command "Expand-Archive terraform.zip -DestinationPath ."
    set PATH=%PATH%;%CD%
    terraform -version
  displayName: 'Install Terraform'
  workingDirectory: 'C:\PhillipG'

- script: |
    echo "Planning Terraform deployment..."
    terraform plan -out=tfplan
  displayName: 'Terraform Plan'
  workingDirectory: 'C:\PhillipG'

- script: |
    echo "Applying Terraform plan..."
    terraform apply -auto-approve tfplan
  displayName: 'Terraform Apply'
  workingDirectory: 'C:\PhillipG'