trigger:
  branches:
    include:
      - main  # or master, depending on your default branch

pool:
  vmImage: 'ubuntu-latest'  # or 'windows-latest' for .NET or other environments

steps:
- task: UseNode@2  # Use the Node.js version specified in your repository
  inputs:
    versionSpec: '16.x'  # specify the Node.js version
    addToPath: true

- task: NodeTool@1  # Installs Node.js on the agent
  inputs:
    versionSpec: '16.x'

- script: |
    npm install
    npm run build  # Add your build step here, if applicable
  displayName: 'Install dependencies and build'

- task: AzureWebApp@1  # Azure Web App Deployment task
  inputs:
    azureSubscription: 'AzureRM-Connection'  # Connect your Azure subscription to Azure DevOps
    appName: 'YourWebAppName69'  # The name of your Azure Web App
    package: $(Build.ArtifactStagingDirectory)/your-artifact-path  # Path to your app's build output
