# Azure Pipelines YAML for Node.js App Deployment with Workload Identity Federation

trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'windows-latest'

variables:
  NODE_VERSION: '16.x'
  BUILD_DIR: 'build'
  ARTIFACT_NAME: 'app.zip'
  AZURE_WEBAPP_NAME: 'YourWebAppName'  # Replace with your actual Azure Web App name
  AZURE_SERVICE_CONNECTION: 'AzureRM-Connection'  # Replace with your authorized service connection name

steps:
# Step 1: Set up Node.js
- task: UseNode@1
  inputs:
    version: $(NODE_VERSION)

# Step 2: Install dependencies
- script: |
    npm install
  displayName: 'Install Dependencies'

# Step 3: Build the app
- script: |
    npm run build
  displayName: 'Build the App'

# Step 4: Archive build output
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/$(BUILD_DIR)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(ARTIFACT_NAME)'
    replaceExistingArchive: true
  displayName: 'Archive Build Output'

# Step 5: Deploy to Azure Web App
- task: AzureWebApp@1
  inputs:
    azureSubscription: $(AZURE_SERVICE_CONNECTION)
    appName: $(AZURE_WEBAPP_NAME)
    package: '$(Build.ArtifactStagingDirectory)/$(ARTIFACT_NAME)'
  displayName: 'Deploy to Azure Web App'
