trigger:
- main

pool:
  name: AzureVM-Pool

variables:
  terraformVersion: '1.8.5'
  terraformPath: 'C:\terraform\terraform.exe'
  workingDir: '$(Build.SourcesDirectory)'

steps:

# ------------------------------------------------------------
# 0. Checkout Repo and Verify Contents
# ------------------------------------------------------------
- checkout: self

- task: PowerShell@2
  displayName: 'Check for main.tf after checkout'
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "🔍 Checking for main.tf after checkout"
      Get-ChildItem -Path "$(Build.SourcesDirectory)" -Recurse -Filter main.tf

# ------------------------------------------------------------
# 1. Install Terraform (if not found)
# ------------------------------------------------------------
- task: PowerShell@2
  displayName: 'Install Terraform'
  inputs:
    targetType: 'inline'
    script: |
      if (-Not (Test-Path "$(terraformPath)")) {
        Write-Host "Terraform not found. Installing version $(terraformVersion)..."
        New-Item -ItemType Directory -Force -Path "C:\terraform" | Out-Null
        $zipUrl = "https://releases.hashicorp.com/terraform/$(terraformVersion)/terraform_$(terraformVersion)_windows_amd64.zip"
        Invoke-WebRequest -Uri $zipUrl -OutFile "terraform.zip"
        Expand-Archive -Path "terraform.zip" -DestinationPath "C:\terraform" -Force
        Write-Host "✅ Terraform installed at C:\terraform"
      } else {
        Write-Host "✅ Terraform already installed at $(terraformPath)."
      }

# ------------------------------------------------------------
# 2. Terraform Init
# ------------------------------------------------------------
- task: PowerShell@2
  displayName: 'Terraform Init'
  inputs:
    targetType: 'filePath'
    filePath: '$(Build.SourcesDirectory)/terraform-init.ps1'
    workingDirectory: '$(Build.SourcesDirectory)'
  env:
    ARM_USE_OIDC: 'true'
    ARM_CLIENT_ID: $(AZURE_CLIENT_ID)
    ARM_TENANT_ID: $(AZURE_TENANT_ID)
    ARM_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)

# ------------------------------------------------------------
# 3. Terraform Validate
# ------------------------------------------------------------
- task: PowerShell@2
  displayName: 'Terraform Validate'
  inputs:
    targetType: 'filePath'
    filePath: '$(Build.SourcesDirectory)/terraform-validate.ps1'
    workingDirectory: '$(Build.SourcesDirectory)'
  env:
    ARM_USE_OIDC: 'true'
    ARM_CLIENT_ID: $(AZURE_CLIENT_ID)
    ARM_TENANT_ID: $(AZURE_TENANT_ID)
    ARM_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)

# ------------------------------------------------------------
# 4. Terraform Plan
# ------------------------------------------------------------
- task: PowerShell@2
  displayName: 'Terraform Plan'
  inputs:
    targetType: 'filePath'
    filePath: '$(Build.SourcesDirectory)/terraform-plan.ps1'
    workingDirectory: '$(Build.SourcesDirectory)'
  env:
    ARM_USE_OIDC: 'true'
    ARM_CLIENT_ID: $(AZURE_CLIENT_ID)
    ARM_TENANT_ID: $(AZURE_TENANT_ID)
    ARM_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)

# ------------------------------------------------------------
# 5. Terraform Apply (manual runs only)
# ------------------------------------------------------------
- task: PowerShell@2
  displayName: 'Terraform Apply'
  condition: and(succeeded(), eq(variables['Build.Reason'], 'Manual'))
  inputs:
    targetType: 'filePath'
    filePath: '$(Build.SourcesDirectory)/terraform-apply.ps1'
    workingDirectory: '$(Build.SourcesDirectory)'
  env:
    ARM_USE_OIDC: 'true'
    ARM_CLIENT_ID: $(AZURE_CLIENT_ID)
    ARM_TENANT_ID: $(AZURE_TENANT_ID)
    ARM_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
