trigger:
  branches:
    include:
      - main

pool:
  name: 'AzureVM-Pool'  # Your self-hosted agent pool

variables:
  TF_VERSION: '1.5.7'
  TF_WORKING_DIR: 'terraform'

steps:
# Install Terraform manually (since no marketplace task on self-hosted agent)
- powershell: |
    Invoke-WebRequest -Uri "https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_windows_amd64.zip" -OutFile "terraform.zip"
    Expand-Archive -Path "terraform.zip" -DestinationPath "$(Agent.ToolsDirectory)\terraform"
    $env:PATH += ";$(Agent.ToolsDirectory)\terraform"
    terraform -version
  displayName: 'Install Terraform'

# Authenticate to Azure using OIDC
- task: AzureCLI@2
  inputs:
    azureSubscription: 'My-OIDC-Service-Connection'  # Replace with your federated service connection name
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az account show
  displayName: 'Verify Azure OIDC Authentication'

# Terraform Init
- powershell: |
    terraform init
  workingDirectory: '$(TF_WORKING_DIR)'
  displayName: 'Terraform Init'

# Terraform Plan
- powershell: |
    terraform plan -out=tfplan
  workingDirectory: '$(TF_WORKING_DIR)'
  displayName: 'Terraform Plan'

# Terraform Apply
- powershell: |
    terraform apply -auto-approve tfplan
  workingDirectory: '$(TF_WORKING_DIR)'
  displayName: 'Terraform Apply'