trigger:
  branches:
    include:
      - main

pool:
  name: windowsagent  # Replace with your actual agent pool name

variables:
  TF_VAR_subscription_id: $(subscriptionId)
  TF_VAR_tenant_id: $(tenantId)
  TF_VAR_client_id: $(servicePrincipalId)
  TF_VAR_client_secret: $(servicePrincipalKey)
  TF_VAR_object_id: $(objectId)

steps:
- checkout: none  # Skip repo checkout since you're using a local folder

- script: |
    echo "Initializing Terraform..."
    terraform init
  displayName: 'Terraform Init'
  workingDirectory: 'C:\PhillipG'

- script: |
    echo "Planning Terraform deployment..."
    terraform plan -out=tfplan
  displayName: 'Terraform Plan'
  workingDirectory: 'C:\PhillipG'

- script: |
    echo "Applying Terraform plan..."
    terraform apply -auto-approve tfplan
  displayName: 'Terraform Apply'
  workingDirectory: 'C:\PhillipG'