trigger:
  - main

pool:
  name: windowsagent  # Your self-hosted agent pool
  demands:
    - Agent.OS -equals Windows_NT

steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '6.0.x'

  - script: dotnet build
    displayName: 'Build .NET project'

  - script: dotnet test
    displayName: 'Run unit tests'

  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        Write-Host "Top 5 CPU-consuming processes"
        Get-Process | Sort-Object CPU -Descending | Select-Object -First 5
