trigger:
  branches:
    include:
      - main

stages:
- stage: DeployKeyVault
  jobs:
  - job: Deploy
    pool:
      name: windowsagent
    
    steps:
    - checkout: self

    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureRM-Connection'  # Replace with your actual AzureRM service connection name
        scriptType: 'ps'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az group create --name my-rg --location eastus
        displayName: 'Create Resource Group'

    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: 'AzureRM-Connection'
        subscriptionId: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'  # Replace with your actual subscription ID
        action: 'Create Or Update Resource Group'
        resourceGroupName: 'my-rg'
        location: 'eastus'
        templateLocation: 'Linked artifact'
        csmFile: 'infra/keyvault.json'
        csmParametersFile: 'infra/keyvault.parameters.json'
        deploymentMode: 'Incremental'

- stage: UseSecrets
  dependsOn: DeployKeyVault
  jobs:
  - job: RetrieveSecrets
    pool:
      name: windowsagent

    steps:
    - task: AzureKeyVault@2
      inputs:
        azureSubscription: 'AzureRM-Connection'
        KeyVaultName: 'my-secure-kv'
        SecretsFilter: '*'
        RunAsPreJob: true

    - script: echo "Secret value is $(MySecret)"
      displayName: 'Print Secret'