trigger:
  branches:
    include:
      - main

pool:
  name: 'AzureVM-Pool'  # Or use vmImage if hosted agent

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'My-OIDC-Service-Connection'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az account show
  displayName: 'Verify Azure OIDC Authentication'