trigger:
  branches:
    include:
      - main

pool:
  name: windowsagent  # Your self-hosted or MS-hosted agent pool

variables:
  subscriptionId: '7b4156be-c801-4a1d-a9c5-418dc1158bb7'
  resourceGroup: 'rg-phillipg-dev'
  location: 'westus2'
  storageAccount: 'phillipgstorage'
  containerName: 'tfstate'
  keyVaultName: 'phillipg-kv'
  backendKey: 'terraform.tfstate'

# 1️⃣ Retrieve secrets from Azure Key Vault
steps:
- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'AzureRM-Connection'
    KeyVaultName: '$(keyVaultName)'
    SecretsFilter: '*'
    RunAsPreJob: true

# 2️⃣ Bootstrap backend resources using Azure CLI (auth handled by service connection)
- task: AzureCLI@2
  displayName: 'Bootstrap Azure Backend'
  inputs:
    azureSubscription: 'AzureRM-Connection'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    workingDirectory: 'C:\PhillipG'
    inlineScript: |
      az account set --subscription "$(subscriptionId)"

      az group create --name "$(resourceGroup)" --location "$(location)"

      az keyvault create --name "$(keyVaultName)" `
        --resource-group "$(resourceGroup)" `
        --location "$(location)" `
        --enable-rbac-authorization true

      az storage account create `
        --name "$(storageAccount)" `
        --resource-group "$(resourceGroup)" `
        --location "$(location)" `
        --sku Standard_LRS `
        --kind StorageV2

      az storage container create `
        --name "$(containerName)" `
        --account-name "$(storageAccount)"

# 3️⃣ Wait for Azure propagation
- powershell: |
    Write-Host "Waiting for Azure resources to propagate..."
    Start-Sleep -Seconds 30
  displayName: 'Wait for Azure Propagation'

# 4️⃣ Verify resources
- task: AzureCLI@2
  displayName: 'Verify Azure Resources'
  inputs:
    azureSubscription: 'AzureRM-Connection'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az group show --name "$(resourceGroup)"
      az storage account show --name "$(storageAccount)" --resource-group "$(resourceGroup)"

# 5️⃣ Create Terraform backend config dynamically
- powershell: |
    @"
    terraform {
      backend "azurerm" {
        resource_group_name  = "$(resourceGroup)"
        storage_account_name = "$(storageAccount)"
        container_name       = "$(containerName)"
        key                  = "$(backendKey)"
      }
    }
    "@ | Out-File -FilePath "C:\PhillipG\backend.tf" -Encoding utf8
  displayName: 'Write Terraform Backend Config'

# 6️⃣ Terraform Init
- powershell: |
    terraform init -reconfigure
  displayName: 'Terraform Init'
  workingDirectory: 'C:\PhillipG'

# 7️⃣ Terraform Plan
- powershell: |
    terraform plan -var-file="C:/PhillipG/terraform.tfvars" -out=tfplan
  displayName: 'Terraform Plan'
  workingDirectory: 'C:\PhillipG'
