trigger:
  branches:
    include:
      - main

pool:
  name: 'AzureVM-Pool'   # Your self-hosted or Microsoft-hosted agent

variables:
  terraformVersion: '1.9.8'
  workingDirectory: ''    # Will be dynamically detected

stages:
# ==========================================
# Stage 1: Terraform Plan
# ==========================================
- stage: Plan
  displayName: 'Terraform Plan'
  jobs:
  - job: TerraformPlan
    displayName: 'Terraform Init, Validate, Plan'
    steps:
    # ------------------------------------------
    # Checkout repo
    # ------------------------------------------
    - checkout: self
      displayName: 'Checkout code'

    # ------------------------------------------
    # Detect Terraform Directory (PowerShell for Windows)
    # ------------------------------------------
    - powershell: |
        $tfFiles = Get-ChildItem -Path . -Recurse -Filter *.tf | Select-Object -First 1
        if ($tfFiles) {
          $workDir = $tfFiles.DirectoryName
          Write-Host "##vso[task.setvariable variable=workingDirectory]$workDir"
          Write-Host "Terraform working directory: $workDir"
        } else {
          Write-Error "No Terraform (.tf) files found in repo."
        }
      displayName: 'Detect Terraform Directory'

    # ------------------------------------------
    # Install Terraform
    # ------------------------------------------
    - task: TerraformInstaller@1
      displayName: 'Install Terraform'
      inputs:
        terraformVersion: $(terraformVersion)

    # ------------------------------------------
    # Terraform Init
    # ------------------------------------------
    - script: terraform init -upgrade
      displayName: 'Terraform Init'
      workingDirectory: $(workingDirectory)
      env:
        ARM_USE_OIDC: true
        ARM_CLIENT_ID: "61ca0367-ed98-476b-9c79-73fa2b7ae041"
        ARM_SUBSCRIPTION_ID: "7b4156be-c801-4a1d-a9c5-418dc1158bb7"
        ARM_TENANT_ID: "5d08b221-8006-4709-ac38-d9c398886bc3"

    # ------------------------------------------
    # Terraform Validate
    # ------------------------------------------
    - script: terraform validate
      displayName: 'Terraform Validate'
      workingDirectory: $(workingDirectory)

    # ------------------------------------------
    # Terraform Plan
    # ------------------------------------------
    - script: terraform plan -out=tfplan
      displayName: 'Terraform Plan'
      workingDirectory: $(workingDirectory)
      env:
        ARM_USE_OIDC: true
        ARM_CLIENT_ID: "61ca0367-ed98-476b-9c79-73fa2b7ae041"
        ARM_SUBSCRIPTION_ID: "7b4156be-c801-4a1d-a9c5-418dc1158bb7"
        ARM_TENANT_ID: "5d08b221-8006-4709-ac38-d9c398886bc3"

    # ------------------------------------------
    # Publish Terraform Plan Artifact
    # ------------------------------------------
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Terraform Plan Artifact'
      inputs:
        pathToPublish: '$(workingDirectory)/tfplan'
        artifactName: 'terraform-plan'

# ==========================================
# Stage 2: Terraform Apply (manual approval recommended)
# ==========================================
- stage: Apply
  displayName: 'Terraform Apply'
  dependsOn: Plan
  condition: succeeded()
  jobs:
  - job: TerraformApply
    displayName: 'Apply Terraform'
    steps:
    # ------------------------------------------
    # Checkout repo
    # ------------------------------------------
    - checkout: self

    # ------------------------------------------
    # Download Plan Artifact
    # ------------------------------------------
    - download: current
      artifact: terraform-
